import { useState, type ReactNode } from "react";
import { Link } from "react-router";

import { ContentCard, EffectIcon, EquipmentSlot, Glyph, Portrait, ResourceBar, type GlyphName } from "../ui/Display";
import { tableNavigation, type TableRole } from "./tableNavigation";

type Role = TableRole;
type View = "overview" | "character" | "activity" | "cards" | "room" | "guide";

const members = [
  { name: "Ari Teste", subtitle: "Sentinela · Humano", hue: "violet" as const, status: "Em campo" },
  { name: "Mira Voss", subtitle: "Ocultista · Élfica", hue: "copper" as const, status: "Em campo" },
  { name: "Théo Vale", subtitle: "Gatuno · Humano", hue: "teal" as const, status: "Em campo" },
];

function SectionHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description?: string; action?: ReactNode }) {
  return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</div>;
}

function Sidebar({ role, view, navigate }: { role: Role; view: View; navigate: (view: View) => void }) {
  const items = tableNavigation[role];
  return <aside className="sidebar">
    <div className="brand"><span className="brand__mark"><Glyph name="spark" size={24} /></span><div><strong>CURSED</strong><small>PLATAFORMA RPG</small></div></div>
    <div className="sidebar__campaign"><span className="eyebrow">CAMPANHA ATUAL</span><strong>O Véu de Aram</strong><small><span className="live-dot" /> Sessão 12 · em preparação</small></div>
    <div className="sidebar__label">MESA</div>
    <nav aria-label="Navegação da mesa" className="sidebar__nav">{items.map((item) => <button key={item.id} type="button" className={`nav-item ${view === item.id ? "nav-item--active" : ""}`} aria-current={view === item.id ? "page" : undefined} onClick={() => navigate(item.id)}><Glyph name={item.icon} size={19} /><span>{item.label}</span>{view === item.id && <span className="nav-item__accent" />}</button>)}</nav>
    <div className="sidebar__bottom"><button type="button" className={`nav-item ${view === "guide" ? "nav-item--active" : ""}`} onClick={() => navigate("guide")}><Glyph name="settings" size={19} /><span>Guia visual</span></button><div className="sidebar__edition">PRÉVIA INTERATIVA <span>·</span> 2026</div></div>
  </aside>;
}

function MobileNav({ role, view, navigate }: { role: Role; view: View; navigate: (view: View) => void }) {
  const items = tableNavigation[role];
  return <nav className="mobile-nav" aria-label="Navegação móvel da mesa">{items.map((item) => <button key={item.id} type="button" aria-current={view === item.id ? "page" : undefined} className={view === item.id ? "mobile-nav__active" : ""} onClick={() => navigate(item.id)}><Glyph name={item.icon} size={20} /><span>{item.label}</span></button>)}</nav>;
}

function PreviewHeader({ role, onRoleChange, onGuide, view }: { role: Role; onRoleChange: (role: Role) => void; onGuide: () => void; view: View }) {
  const title = view === "guide" ? "Guia visual" : role === "narrador" ? "Painel do Narrador" : "Painel do Jogador";
  return <header className="preview-header"><div className="preview-header__title"><span className="eyebrow">O VÉU DE ARAM <span className="header-separator">/</span> PRÉVIA</span><strong>{title}</strong></div><div className="preview-header__actions"><span className="preview-badge"><Glyph name="eye" size={14} /> Dados ilustrativos</span><button className="header-guide" type="button" onClick={onGuide} aria-label="Abrir guia visual"><Glyph name="settings" size={18} /></button><label className="role-switch"><span className="sr-only">Visualizar como</span><select value={role} onChange={(event) => onRoleChange(event.target.value as Role)}><option value="narrador">Narrador</option><option value="jogador">Jogador</option></select><Glyph name="chevron" size={14} /></label><Portrait name={role === "narrador" ? "Narrador" : "Ari Teste"} hue={role === "narrador" ? "copper" : "violet"} /></div></header>;
}

function StatCard({ icon, value, label, detail, tone = "gold" }: { icon: GlyphName; value: string; label: string; detail: string; tone?: "gold" | "violet" | "teal" | "rose" }) {
  return <article className={`stat-card stat-card--${tone}`}><span className="stat-card__icon"><Glyph name={icon} size={21} /></span><strong>{value}</strong><span>{label}</span><small>{detail}</small></article>;
}

function CharacterTile({ name, subtitle, hue, status, onOpen }: { name: string; subtitle: string; hue: "violet" | "copper" | "teal"; status: string; onOpen: () => void }) {
  return <button type="button" className="character-tile" onClick={onOpen}><Portrait name={name} hue={hue} /><span className="character-tile__text"><strong>{name}</strong><small>{subtitle}</small></span><span className="status-pill"><span className="live-dot" />{status}</span><Glyph name="chevron" size={17} className="character-tile__arrow" /></button>;
}

function ActivityList({ compact = false }: { compact?: boolean }) {
  const entries = [
    { symbol: "✦", tone: "violet", name: "Mira Voss", action: "recebeu um novo efeito", subject: "Véu Protetor", time: "há 12 min" },
    { symbol: "◆", tone: "teal", name: "Ari Teste", action: "equipou", subject: "Lâmina da Vigília", time: "há 38 min" },
    { symbol: "◈", tone: "gold", name: "Narrador", action: "preparou a sessão", subject: "A Torre Silenciosa", time: "ontem" },
    { symbol: "✧", tone: "rose", name: "Théo Vale", action: "atualizou a ficha", subject: "Personalidade", time: "ontem" },
  ];
  return <div className="activity-list">{entries.slice(0, compact ? 3 : undefined).map((entry) => <div className="activity-entry" key={`${entry.name}-${entry.subject}`}><span className={`activity-entry__symbol activity-entry__symbol--${entry.tone}`} aria-hidden="true">{entry.symbol}</span><div><p><strong>{entry.name}</strong> {entry.action} <em>{entry.subject}</em></p><small>{entry.time}</small></div></div>)}</div>;
}

function NarratorOverview({ navigate }: { navigate: (view: View) => void }) {
  return <div className="screen-content"><section className="hero-panel"><div className="hero-panel__stars" aria-hidden="true" /><div className="hero-panel__copy"><span className="eyebrow">SEXTA-FEIRA, NOITE DE JOGO</span><h1>A história espera<br /><em>por vocês.</em></h1><p>Continue a campanha de onde o grupo parou. Personagens, escolhas e consequências estão reunidos aqui.</p><div className="hero-panel__actions"><button className="button button--primary" type="button" onClick={() => navigate("room")}>Abrir sala <Glyph name="arrow" size={18} /></button><button className="button button--ghost" type="button" onClick={() => navigate("activity")}>Ver registro</button></div></div><div className="hero-panel__sigil" aria-hidden="true"><span>✧</span><div className="hero-panel__sigil-ring" /></div><span className="hero-panel__corner">CAPÍTULO III <span>·</span> O VÉU DE ARAM</span></section>
    <section className="stats-grid" aria-label="Resumo da mesa"><StatCard icon="users" value="03" label="Aventureiros" detail="Prontos para a sessão" tone="violet" /><StatCard icon="scroll" value="02" label="Solicitações" detail="Aguardando revisão" tone="gold" /><StatCard icon="spark" value="03" label="Efeitos ativos" detail="No grupo" tone="teal" /><StatCard icon="clock" value="12" label="Sessões" detail="Nesta campanha" tone="rose" /></section>
    <div className="dashboard-columns"><section className="panel"><SectionHeading eyebrow="COMPANHIA" title="O grupo em campo" action={<button className="text-action" type="button" onClick={() => navigate("character")}>Ver fichas <Glyph name="arrow" size={16} /></button>} /><div className="character-list">{members.map((member) => <CharacterTile key={member.name} {...member} onOpen={() => navigate("character")} />)}</div><div className="panel__foot"><Glyph name="shield" size={17} /><span>Visibilidade e permissões dependem da mesa.</span></div></section><section className="panel"><SectionHeading eyebrow="O QUE MUDOU" title="Atividade recente" action={<button className="text-action" type="button" onClick={() => navigate("activity")}>Abrir registro <Glyph name="arrow" size={16} /></button>} /><ActivityList compact /></section></div>
    <section className="chapter-panel"><div><span className="eyebrow">PRÓXIMA CENA</span><h2>A Torre Silenciosa</h2><p>Um espaço para preparar a cena e acompanhar o ritmo da sessão.</p></div><span className="chapter-panel__symbol" aria-hidden="true">✧</span></section>
  </div>;
}

function PlayerOverview({ navigate }: { navigate: (view: View) => void }) {
  return <div className="screen-content"><section className="hero-panel hero-panel--player"><div className="hero-panel__stars" aria-hidden="true" /><div className="hero-panel__copy"><span className="eyebrow">O VÉU DE ARAM · SESSÃO 12</span><h1>Sua história<br /><em>continua aqui.</em></h1><p>Veja como Ari está antes da próxima sessão e acompanhe o grupo.</p><div className="hero-panel__actions"><button className="button button--primary" type="button" onClick={() => navigate("character")}>Abrir minha ficha <Glyph name="arrow" size={18} /></button><button className="button button--ghost" type="button" onClick={() => navigate("room")}>Ver sala</button></div></div><div className="hero-panel__sigil" aria-hidden="true"><span>✦</span><div className="hero-panel__sigil-ring" /></div></section><section className="panel"><SectionHeading eyebrow="COMPANHIA" title="Seu grupo" /><div className="character-list">{members.map((member) => <CharacterTile key={member.name} {...member} onOpen={() => navigate("character")} />)}</div></section></div>;
}

function CharacterSheet({ role }: { role: Role }) {
  const [tab, setTab] = useState<"resumo" | "atributos" | "equipamento">("resumo");
  return <div className="screen-content"><div className="page-intro"><span className="eyebrow">FICHA VIVA <span className="header-separator">/</span> {role === "narrador" ? "PERSONAGENS" : "MEU PERSONAGEM"}</span><h1>Ari Teste</h1><p>Uma visão do personagem durante o jogo. Os valores abaixo são ilustrativos.</p></div><section className="character-hero"><div className="character-hero__portrait"><Portrait name="Ari Teste" hue="violet" size="large" /><span className="character-hero__crest">✦</span></div><div className="character-hero__identity"><span className="eyebrow">SENTINELA · HUMANO</span><h2>Ari Teste</h2><p>“Proteger o grupo, mesmo quando a estrada desaparece.”</p><div className="tag-row"><span className="tag">Guerreiro</span><span className="tag">Sentinela</span><span className="tag tag--accent">Em campo</span></div></div><div className="character-hero__resources"><ResourceBar label="Pontos de Vida" current={18} max={24} kind="life" /><ResourceBar label="Pontos de Poder" current={7} max={12} kind="power" /><ResourceBar label="Foco" current={3} max={4} kind="focus" /></div></section><div className="effect-strip"><div><span className="eyebrow">ESTADO ATUAL</span><strong>Efeitos ativos</strong></div><EffectIcon name="Véu Protetor" symbol="✧" description="Proteção temporária. Origem: Mira Voss. Duração e encerramento ainda serão definidos na ficha real." /><EffectIcon name="Vigília" symbol="◈" tone="gold" description="Efeito ilustrativo de atenção durante a sessão." /><EffectIcon name="Passo Leve" symbol="◇" tone="teal" description="Efeito ilustrativo de movimento." /><span className="effect-strip__hint">Foque ou toque para ver detalhes</span></div><div className="sheet-tabs" role="tablist" aria-label="Seções da ficha"><button type="button" role="tab" aria-selected={tab === "resumo"} onClick={() => setTab("resumo")}>Visão geral</button><button type="button" role="tab" aria-selected={tab === "atributos"} onClick={() => setTab("atributos")}>Atributos e perícias</button><button type="button" role="tab" aria-selected={tab === "equipamento"} onClick={() => setTab("equipamento")}>Equipamento</button></div>
    {tab === "resumo" && <div className="sheet-columns"><section className="panel"><SectionHeading eyebrow="IDENTIDADE" title="Quem é Ari" /><p className="body-copy">Uma sentinela que escolheu permanecer com o grupo quando o caminho mais seguro era partir. Seus vínculos e escolhas orientam a história tanto quanto seus números.</p><div className="detail-grid"><div><span className="eyebrow">ORIGEM</span><strong>Fronteira de Aram</strong></div><div><span className="eyebrow">ALINHAMENTO</span><strong>Neutro</strong></div><div><span className="eyebrow">LEMA</span><strong>Proteger o grupo</strong></div><div><span className="eyebrow">PAPEL</span><strong>Defesa e vigília</strong></div></div></section><section className="panel"><SectionHeading eyebrow="EM DESTAQUE" title="Recursos e escolhas" /><div className="feature-list"><div><span className="feature-list__icon"><Glyph name="shield" size={20} /></span><div><strong>Defesa</strong><small>Valor e fontes ficarão consultáveis na ficha.</small></div><b>14</b></div><div><span className="feature-list__icon"><Glyph name="star" size={20} /></span><div><strong>Prontidão</strong><small>Preparado para perceber mudanças na cena.</small></div><b>+1</b></div><div><span className="feature-list__icon"><Glyph name="book" size={20} /></span><div><strong>Habilidades</strong><small>Conteúdos aprendidos e disponíveis terão estados distintos.</small></div><b>03</b></div></div></section></div>}
    {tab === "atributos" && <div className="sheet-columns"><section className="panel"><SectionHeading eyebrow="BASE MECÂNICA" title="Atributos" /><div className="attribute-list">{[["Força", "+2", "Potência física"], ["Destreza", "+1", "Precisão e movimento"], ["Intelecto", "+0", "Conhecimento"], ["Vontade", "+2", "Resolução"]].map(([name, value, detail]) => <div key={name}><span><strong>{name}</strong><small>{detail}</small></span><b>{value}</b></div>)}</div></section><section className="panel"><SectionHeading eyebrow="ESPECIALIDADES" title="Perícias" /><div className="attribute-list">{[["Prontidão", "+1", "Atenção ao ambiente"], ["Atletismo", "+2", "Esforço e movimento"], ["Sobrevivência", "+1", "Caminhos e abrigo"]].map(([name, value, detail]) => <div key={name}><span><strong>{name}</strong><small>{detail}</small></span><b>{value}</b></div>)}</div></section></div>}
    {tab === "equipamento" && <div className="sheet-columns"><section className="panel"><SectionHeading eyebrow="PRONTO PARA USO" title="Equipado" /><div className="equipment-list"><EquipmentSlot category="ARMA" item="Lâmina da Vigília" detail="Efeito aplicado enquanto equipada" icon="sword" /><EquipmentSlot category="ARMADURA" item="Cota do Guardião" detail="Proteção e mobilidade" icon="shield" /></div></section><section className="panel"><SectionHeading eyebrow="PERTENCES" title="Inventário" /><div className="equipment-list"><EquipmentSlot category="SUPRIMENTO" item="Kit de viagem" detail="Quantidade: 1" icon="bag" /><EquipmentSlot category="OBJETO" item="Mapa dobrado" detail="Encontrado na última sessão" icon="map" /></div></section></div>}
  </div>;
}

function ActivityPage() {
  return <div className="screen-content"><div className="page-intro"><span className="eyebrow">HISTÓRIA DA MESA</span><h1>Registro</h1><p>Ações confirmadas terão contexto, autoria e momento. Esta linha do tempo é ilustrativa.</p></div><section className="panel panel--wide"><SectionHeading eyebrow="SESSÃO 12" title="Movimentos recentes" /><ActivityList /></section></div>;
}

function CardsPage() {
  return <div className="screen-content"><div className="page-intro"><span className="eyebrow">CONTEÚDO DA CAMPANHA</span><h1>Biblioteca de cartas</h1><p>Habilidades, magias e itens terão apresentação comum, com ciclos de jogo próprios.</p></div><div className="card-grid"><ContentCard kind="HABILIDADE · DISPONÍVEL" title="Vigília Inabalável" description="Uma promessa feita ao grupo se torna atenção constante aos perigos da estrada." meta="Disponível para aprendizado" emblem="✧" /><ContentCard kind="MAGIA · APRENDIDA" title="Véu Protetor" description="Um manto de energia protege um aliado no momento de maior necessidade." meta="Uso sujeito aos custos da carta" emblem="✦" /><ContentCard kind="ITEM · INVENTÁRIO" title="Lâmina da Vigília" description="Uma arma marcada por histórias de guardiões que nunca abandonaram seu posto." meta="Possuída · equipada" emblem="⚔" /></div><p className="preview-note"><Glyph name="eye" size={17} /> Conteúdo visual demonstrativo; custos e regras definitivos virão dos dados validados.</p></div>;
}

function RoomPage({ role }: { role: Role }) {
  return <div className="screen-content"><div className="page-intro"><span className="eyebrow">MÓDULO OPCIONAL</span><h1>Sala da mesa</h1><p>Uma prévia de como a cena e o grupo podem dividir a mesma superfície.</p></div><section className="room-layout"><div className="room-map"><div className="room-map__scene"><span className="eyebrow">CENA ATUAL</span><strong>A Torre Silenciosa</strong></div><span className="map-token map-token--ari" title="Ari Teste">AT</span><span className="map-token map-token--mira" title="Mira Voss">MV</span><span className="map-token map-token--theo" title="Théo Vale">TV</span><div className="room-map__label">PRÉVIA DO GRID · SEM SINCRONIZAÇÃO</div></div><aside className="panel room-party"><SectionHeading eyebrow="NA CENA" title="Companhia" /><div className="character-list">{members.map((member) => <div className="character-tile character-tile--static" key={member.name}><Portrait name={member.name} hue={member.hue} /><span className="character-tile__text"><strong>{member.name}</strong><small>{member.subtitle}</small></span></div>)}</div><p className="room-party__note">{role === "narrador" ? "O Narrador terá controles de cena e visibilidade quando o módulo estiver conectado." : "Você verá somente informações reveladas ao grupo."}</p></aside></section></div>;
}

function GuidePage() {
  return <div className="screen-content"><div className="page-intro"><span className="eyebrow">DESIGN SYSTEM · REFERÊNCIA</span><h1>Um mundo em detalhes</h1><p>Cores, superfícies e componentes que dão forma à nova plataforma.</p></div><section className="panel panel--wide"><SectionHeading eyebrow="PALETA" title="Cor e atmosfera" /><div className="swatch-grid">{[["Noite", "var(--bg)", "#0C0D12"], ["Superfície", "var(--surface)", "#181922"], ["Ouro", "var(--gold)", "#E4BD78"], ["Arcano", "var(--violet)", "#A997E8"], ["Vida", "var(--red)", "#DF887D"], ["Aliança", "var(--teal)", "#80C8B8"]].map(([name, color, hex]) => <div className="swatch" key={name}><span style={{ background: color }} /><strong>{name}</strong><small>{hex}</small></div>)}</div></section><div className="guide-columns"><section className="panel"><SectionHeading eyebrow="TIPOGRAFIA" title="Voz e leitura" /><p className="guide-display">Entre sombras<br /><em>e escolhas.</em></p><p className="body-copy">A voz de fantasia usa títulos com personalidade. A interface mantém textos de jogo claros e legíveis.</p></section><section className="panel"><SectionHeading eyebrow="COMPONENTES" title="Estados e recursos" /><ResourceBar label="Pontos de Vida" current={18} max={24} kind="life" /><ResourceBar label="Pontos de Poder" current={7} max={12} kind="power" /><div className="guide-effects"><EffectIcon name="Véu Protetor" symbol="✧" description="Detalhe do efeito" /><EffectIcon name="Vigília" symbol="◈" tone="gold" description="Detalhe do efeito" /><EffectIcon name="Passo Leve" symbol="◇" tone="teal" description="Detalhe do efeito" /></div></section></div><section className="panel panel--wide"><SectionHeading eyebrow="COMPONENTES" title="Retrato, equipamento e carta" /><div className="guide-components"><div className="guide-portraits"><Portrait name="Ari Teste" hue="violet" size="large" /><Portrait name="Mira Voss" hue="copper" /><Portrait name="Théo Vale" hue="teal" /></div><EquipmentSlot category="ARMA EQUIPADA" item="Lâmina da Vigília" detail="Efeitos e origem consultáveis" icon="sword" /><ContentCard kind="HABILIDADE" title="Vigília Inabalável" description="Uma carta com procedência e estado próprios." meta="Disponível para aprendizado" emblem="✧" /></div></section><section className="panel panel--wide"><SectionHeading eyebrow="ESTADOS" title="Controles e superfícies" /><div className="guide-actions"><button type="button" className="button button--primary">Ação principal <Glyph name="arrow" size={17} /></button><button type="button" className="button button--secondary">Ação secundária</button><button type="button" className="button button--ghost">Ação discreta</button><button type="button" className="button button--primary" disabled>Indisponível</button></div><p className="body-copy">Ações, foco, contraste e movimento são definidos pelos mesmos tokens visuais.</p></section></div>;
}

export function PreviewApp() {
  const [role, setRole] = useState<Role>("narrador");
  const [view, setView] = useState<View>("overview");
  const navigate = (next: View) => { setView(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const changeRole = (next: Role) => { setRole(next); setView(next === "narrador" ? "overview" : "character"); };
  return <div className="preview-app"><Sidebar role={role} view={view} navigate={navigate} /><div className="preview-main"><PreviewHeader role={role} onRoleChange={changeRole} onGuide={() => navigate("guide")} view={view} /><div className="demo-ribbon"><Glyph name="eye" size={15} /><span>Prévia de interface com dados fictícios. Nenhuma alteração é salva.</span><Link to="/">Ir para entrada real <Glyph name="arrow" size={14} /></Link></div><main id="main-content" className="preview-content">{view === "overview" && (role === "narrador" ? <NarratorOverview navigate={navigate} /> : <PlayerOverview navigate={navigate} />)}{view === "character" && <CharacterSheet role={role} />}{view === "activity" && <ActivityPage />}{view === "cards" && <CardsPage />}{view === "room" && <RoomPage role={role} />}{view === "guide" && <GuidePage />}</main><footer className="preview-footer"><span>CURSED <span>✦</span> PLATAFORMA RPG</span><span>Prévia visual da nova experiência</span></footer></div><MobileNav role={role} view={view} navigate={navigate} /></div>;
}
